version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: runtime-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${BACKEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
    - ./backend/src/Data:/app/Data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: runtime-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VITE_API_URL=http://localhost:5202/api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest